import type { ToolDef } from "../../types.js"
import { readFileTool } from "./read-file.js"
import { writeFileTool } from "./write-file.js"
import { editTool } from "./replace-in-file.js"
import { bashTool } from "./execute-command.js"
import { bashOutputTool } from "./bash-output.js"
import { killBashTool } from "./kill-bash.js"
import { grepTool, listTool } from "./search-files.js"
import { listDefinitionsTool } from "./list-definitions.js"
import { lspTool } from "./lsp-tool.js"
import { readLintsTool } from "./read-lints.js"
import { codebaseSearchTool } from "./codebase-search.js"
import { webFetchTool, webSearchTool } from "./web-fetch.js"
import { globFileSearchTool } from "./glob-file-search.js"
import { useSkillTool } from "./use-skill.js"
import { condenseTool, planExitTool } from "./context-tools.js"
import {
  askFollowupTool,
  todoWriteTool,
} from "./report-and-control.js"
import { parallelTool } from "./parallel.js"
import {
  enterPlanModeTool,
  exitPlanModeTool,
  sendUserMessageTool,
  toolSearchTool,
  taskCreateTool,
  taskGetTool,
  taskListTool,
  taskUpdateTool,
  taskOutputTool,
  taskStopTool,
  teamCreateTool,
  teamListTool,
  teamGetTool,
  teamInboxTool,
  teamAddMemberTool,
  teamAssignTaskTool,
  teamSetMemberStatusTool,
  teamDeleteTool,
  sendMessageTool,
  listRemoteSessionsTool,
  getRemoteSessionTool,
  updateRemoteSessionTool,
  sendRemoteMessageTool,
  interruptRemoteSessionTool,
  reconnectRemoteSessionTool,
  enterWorktreeTool,
  exitWorktreeTool,
  powerShellTool,
  listMcpResourcesTool,
  readMcpResourceTool,
  mcpAuthenticateTool,
  listAgentsTool,
  listPluginsTool,
  getPluginTool,
  runPluginHookTool,
  pluginTrustTool,
  pluginEnableTool,
  pluginConfigureTool,
  pluginValidateTool,
  pluginInstallLocalTool,
  pluginRemoveTool,
  pluginReloadTool,
  planStartWorkflowTool,
  planGetWorkflowTool,
  planAnswerWorkflowTool,
  planCreateResearchTasksTool,
  planDraftWorkflowTool,
  planMaterializeTasksTool,
  planVerifyExecutionTool,
  memoryCreateTool,
  memoryListTool,
  memoryGetTool,
  memoryUpdateTool,
  memoryDeleteTool,
} from "./orchestration-tools.js"

export function getAllBuiltinTools(): ToolDef[] {
  return [
    askFollowupTool,
    todoWriteTool,
    sendUserMessageTool,
    parallelTool,
    toolSearchTool,
    readFileTool,
    listTool,
    listDefinitionsTool,
    lspTool,
    readLintsTool,
    writeFileTool,
    editTool,
    bashTool,
    bashOutputTool,
    killBashTool,
    powerShellTool,
    grepTool,
    codebaseSearchTool,
    webFetchTool,
    webSearchTool,
    globFileSearchTool,
    taskCreateTool,
    taskGetTool,
    taskListTool,
    taskUpdateTool,
    taskOutputTool,
    taskStopTool,
    teamCreateTool,
    teamListTool,
    teamGetTool,
    teamInboxTool,
    teamAddMemberTool,
    teamAssignTaskTool,
    teamSetMemberStatusTool,
    teamDeleteTool,
    sendMessageTool,
    listRemoteSessionsTool,
    getRemoteSessionTool,
    updateRemoteSessionTool,
    sendRemoteMessageTool,
    interruptRemoteSessionTool,
    reconnectRemoteSessionTool,
    enterWorktreeTool,
    exitWorktreeTool,
    listMcpResourcesTool,
    readMcpResourceTool,
    mcpAuthenticateTool,
    listAgentsTool,
    listPluginsTool,
    getPluginTool,
    runPluginHookTool,
    pluginTrustTool,
    pluginEnableTool,
    pluginConfigureTool,
    pluginValidateTool,
    pluginInstallLocalTool,
    pluginRemoveTool,
    pluginReloadTool,
    planStartWorkflowTool,
    planGetWorkflowTool,
    planAnswerWorkflowTool,
    planCreateResearchTasksTool,
    planDraftWorkflowTool,
    planMaterializeTasksTool,
    planVerifyExecutionTool,
    memoryCreateTool,
    memoryListTool,
    memoryGetTool,
    memoryUpdateTool,
    memoryDeleteTool,
    enterPlanModeTool,

    condenseTool,
    planExitTool,
    exitPlanModeTool,

    useSkillTool,
  ]
}

export {
  readFileTool,
  writeFileTool,
  editTool,
  parallelTool,
  bashTool,
  bashOutputTool,
  killBashTool,
  grepTool,
  listTool,
  listDefinitionsTool,
  lspTool,
  readLintsTool,
  codebaseSearchTool,
  webFetchTool,
  webSearchTool,
  globFileSearchTool,
  useSkillTool,
  askFollowupTool,
  todoWriteTool,
  sendUserMessageTool,
  condenseTool,
  planExitTool,
  enterPlanModeTool,
  exitPlanModeTool,
  toolSearchTool,
  taskCreateTool,
  taskGetTool,
  taskListTool,
  taskUpdateTool,
  taskOutputTool,
  taskStopTool,
  teamCreateTool,
  teamListTool,
  teamGetTool,
  teamInboxTool,
  teamAddMemberTool,
  teamAssignTaskTool,
  teamSetMemberStatusTool,
  teamDeleteTool,
  sendMessageTool,
  listRemoteSessionsTool,
  getRemoteSessionTool,
  updateRemoteSessionTool,
  sendRemoteMessageTool,
  interruptRemoteSessionTool,
  reconnectRemoteSessionTool,
  enterWorktreeTool,
  exitWorktreeTool,
  powerShellTool,
  listMcpResourcesTool,
  readMcpResourceTool,
  mcpAuthenticateTool,
  listAgentsTool,
  listPluginsTool,
  getPluginTool,
  runPluginHookTool,
  pluginTrustTool,
  pluginEnableTool,
  pluginConfigureTool,
  pluginValidateTool,
  pluginInstallLocalTool,
  pluginRemoveTool,
  pluginReloadTool,
  planStartWorkflowTool,
  planGetWorkflowTool,
  planAnswerWorkflowTool,
  planCreateResearchTasksTool,
  planDraftWorkflowTool,
  planMaterializeTasksTool,
  planVerifyExecutionTool,
  memoryCreateTool,
  memoryListTool,
  memoryGetTool,
  memoryUpdateTool,
  memoryDeleteTool,
}
