import type { ToolDef } from "../../types.js"
import { readFileTool } from "./read-file.js"
import { toolOutputReadTool } from "./tool-output-read.js"
import { writeFileTool } from "./write-file.js"
import { editTool } from "./replace-in-file.js"
import { applyPatchTool } from "./apply-patch.js"
import { bashTool } from "./execute-command.js"
import { bashOutputTool } from "./bash-output.js"
import { killBashTool } from "./kill-bash.js"
import { grepTool, listTool } from "./search-files.js"
import { listDefinitionsTool } from "./list-definitions.js"
import { lspTool } from "./lsp-tool.js"
import { readLintsTool } from "./read-lints.js"
import { codebaseSearchTool } from "./codebase-search.js"
import { webFetchTool, webSearchTool } from "./web-fetch.js"
import { globFileSearchTool } from "./glob-file-search.js"
import { useSkillTool } from "./use-skill.js"
import { gitInspectTool } from "./git-inspect.js"
import { condenseTool, planExitTool } from "./context-tools.js"
import {
  askFollowupTool,
  todoWriteTool,
} from "./report-and-control.js"
import { parallelTool } from "./parallel.js"
import {
  enterPlanModeTool,
  sendUserMessageTool,
  toolSearchTool,
  taskCreateTool,
  taskGetTool,
  taskListTool,
  taskUpdateTool,
  taskOutputTool,
  taskStopTool,
  teamCreateTool,
  teamListTool,
  teamGetTool,
  teamInboxTool,
  teamAddMemberTool,
  teamAssignTaskTool,
  teamSetMemberStatusTool,
  teamDeleteTool,
  sendMessageTool,
  listRemoteSessionsTool,
  getRemoteSessionTool,
  updateRemoteSessionTool,
  sendRemoteMessageTool,
  interruptRemoteSessionTool,
  reconnectRemoteSessionTool,
  enterWorktreeTool,
  exitWorktreeTool,
  powerShellTool,
  listMcpResourcesTool,
  readMcpResourceTool,
  mcpAuthenticateTool,
  listAgentsTool,
  listPluginsTool,
  getPluginTool,
  runPluginHookTool,
  pluginTrustTool,
  pluginEnableTool,
  pluginConfigureTool,
  pluginValidateTool,
  pluginInstallLocalTool,
  pluginRemoveTool,
  pluginReloadTool,
  planStartWorkflowTool,
  planGetWorkflowTool,
  planAnswerWorkflowTool,
  planCreateResearchTasksTool,
  planDraftWorkflowTool,
  planMaterializeTasksTool,
  planVerifyExecutionTool,
  memoryCreateTool,
  memoryListTool,
  memoryGetTool,
  memoryUpdateTool,
  memoryDeleteTool,
} from "./orchestration-tools.js"

/**
 * Keep the first provider request focused on common coding primitives.
 * Specialized workflow surfaces remain deterministically discoverable through
 * ToolSearch and become executable only at the next provider boundary.
 */
const DEFERRED_BUILTIN_TOOL_NAMES = new Set([
  "PowerShell",
  "EnterWorktree",
  "ExitWorktree",
  "TeamCreate",
  "TeamList",
  "TeamGet",
  "TeamInbox",
  "TeamAddMember",
  "TeamAssignTask",
  "TeamSetMemberStatus",
  "TeamDelete",
  "SendMessage",
  "ListRemoteSessions",
  "GetRemoteSession",
  "UpdateRemoteSession",
  "SendRemoteMessage",
  "InterruptRemoteSession",
  "ReconnectRemoteSession",
  "ListMcpResources",
  "ReadMcpResource",
  "McpAuthenticate",
  "ListAgents",
  "ListPlugins",
  "GetPlugin",
  "RunPluginHook",
  "PluginTrust",
  "PluginEnable",
  "PluginConfigure",
  "PluginValidate",
  "PluginInstallLocal",
  "PluginRemove",
  "PluginReload",
  "PlanStartWorkflow",
  "PlanGetWorkflow",
  "PlanAnswerWorkflow",
  "PlanCreateResearchTasks",
  "PlanDraftWorkflow",
  "PlanMaterializeTasks",
  "PlanVerifyExecution",
  "MemoryCreate",
  "MemoryList",
  "MemoryGet",
  "MemoryUpdate",
  "MemoryDelete",
])

export function getAllBuiltinTools(): ToolDef[] {
  const tools: ToolDef[] = [
    askFollowupTool,
    todoWriteTool,
    sendUserMessageTool,
    parallelTool,
    toolSearchTool,
    readFileTool,
    toolOutputReadTool,
    listTool,
    listDefinitionsTool,
    lspTool,
    readLintsTool,
    writeFileTool,
    editTool,
    applyPatchTool,
    bashTool,
    bashOutputTool,
    killBashTool,
    powerShellTool,
    grepTool,
    codebaseSearchTool,
    webFetchTool,
    webSearchTool,
    globFileSearchTool,
    gitInspectTool,
    taskCreateTool,
    taskGetTool,
    taskListTool,
    taskUpdateTool,
    taskOutputTool,
    taskStopTool,
    teamCreateTool,
    teamListTool,
    teamGetTool,
    teamInboxTool,
    teamAddMemberTool,
    teamAssignTaskTool,
    teamSetMemberStatusTool,
    teamDeleteTool,
    sendMessageTool,
    listRemoteSessionsTool,
    getRemoteSessionTool,
    updateRemoteSessionTool,
    sendRemoteMessageTool,
    interruptRemoteSessionTool,
    reconnectRemoteSessionTool,
    enterWorktreeTool,
    exitWorktreeTool,
    listMcpResourcesTool,
    readMcpResourceTool,
    mcpAuthenticateTool,
    listAgentsTool,
    listPluginsTool,
    getPluginTool,
    runPluginHookTool,
    pluginTrustTool,
    pluginEnableTool,
    pluginConfigureTool,
    pluginValidateTool,
    pluginInstallLocalTool,
    pluginRemoveTool,
    pluginReloadTool,
    planStartWorkflowTool,
    planGetWorkflowTool,
    planAnswerWorkflowTool,
    planCreateResearchTasksTool,
    planDraftWorkflowTool,
    planMaterializeTasksTool,
    planVerifyExecutionTool,
    memoryCreateTool,
    memoryListTool,
    memoryGetTool,
    memoryUpdateTool,
    memoryDeleteTool,
    enterPlanModeTool,

    condenseTool,
    planExitTool,

    useSkillTool,
  ]
  return tools.map((tool) =>
    DEFERRED_BUILTIN_TOOL_NAMES.has(tool.name)
      ? { ...tool, shouldDefer: true }
      : tool,
  )
}

export {
  readFileTool,
  toolOutputReadTool,
  writeFileTool,
  editTool,
  applyPatchTool,
  parallelTool,
  bashTool,
  bashOutputTool,
  killBashTool,
  grepTool,
  listTool,
  listDefinitionsTool,
  lspTool,
  readLintsTool,
  codebaseSearchTool,
  webFetchTool,
  webSearchTool,
  globFileSearchTool,
  gitInspectTool,
  useSkillTool,
  askFollowupTool,
  todoWriteTool,
  sendUserMessageTool,
  condenseTool,
  planExitTool,
  enterPlanModeTool,
  toolSearchTool,
  taskCreateTool,
  taskGetTool,
  taskListTool,
  taskUpdateTool,
  taskOutputTool,
  taskStopTool,
  teamCreateTool,
  teamListTool,
  teamGetTool,
  teamInboxTool,
  teamAddMemberTool,
  teamAssignTaskTool,
  teamSetMemberStatusTool,
  teamDeleteTool,
  sendMessageTool,
  listRemoteSessionsTool,
  getRemoteSessionTool,
  updateRemoteSessionTool,
  sendRemoteMessageTool,
  interruptRemoteSessionTool,
  reconnectRemoteSessionTool,
  enterWorktreeTool,
  exitWorktreeTool,
  powerShellTool,
  listMcpResourcesTool,
  readMcpResourceTool,
  mcpAuthenticateTool,
  listAgentsTool,
  listPluginsTool,
  getPluginTool,
  runPluginHookTool,
  pluginTrustTool,
  pluginEnableTool,
  pluginConfigureTool,
  pluginValidateTool,
  pluginInstallLocalTool,
  pluginRemoveTool,
  pluginReloadTool,
  planStartWorkflowTool,
  planGetWorkflowTool,
  planAnswerWorkflowTool,
  planCreateResearchTasksTool,
  planDraftWorkflowTool,
  planMaterializeTasksTool,
  planVerifyExecutionTool,
  memoryCreateTool,
  memoryListTool,
  memoryGetTool,
  memoryUpdateTool,
  memoryDeleteTool,
}
